### ISSUE TITLE
Couple of issues

### ISSUE THREAD

**Issue by samlipworth** [klebgenomics/Kleborate#84]
Hi Kat/Clara/team,

minor issues encountered whilst using Kleborate:

1) if you do not give an -o  kleborate fails but the error message isn't very helpful, perhaps an error message to tell the user that they need to specify this would be helpful.

2) is there an option to write the output to stdout or to individual files? The use of -o seems problematic if the user wants to run many thousands of genomes on a cluster where each is processed individually as the output is overwitten each time it seems.

Thanks again for your work on this great tool.

Sam

**Comment by katholt** [comment]
Thanks Sam - good suggestions, this is exactly the feedback we need right now :-)

Mary can you action 1 please?

Re 2 - we don't want to write to stdout if multiple input genomes are provided, because they can end up with different headers if they turn out to be different taxa. 

But it could be useful to write to stdout IF a single input is provided, or one file per genome... so either 
1) multiple inputs => one file per species, in directory provided by -o; OR
2) single/multi outputs => one file per genome, filename prefix=strain name [turn this on with some flag, if -o also provided then files go in that directory]; OR
3) single input => stdout (if neither -o nor the single-flag not specified)

So if user runs one job per infile, they can direct the stdout wherever the want; if user runs multiple genomes in serial they can either be one outfile per genome or organised by species in the -o directory
